import jsPDF from "jspdf";

export interface WPSDocument {
  wps_id: string;
  wps_number?: string;
  revision?: number;
  title: string;
  status?: string;
  fields: WPSField[];
  clause_index?: ClauseReference[];
  pqr_matches?: any[];
  audit_summary?: any;
  metadata?: {
    created_by?: string;
    created_at?: string;
    approved_by?: string;
    approved_at?: string;
    company?: string;
    project?: string;
  };
}

export interface WPSField {
  name: string;
  value: string;
  clause?: ClauseReference;
}

export interface ClauseReference {
  code: string;
  clause: string;
  id: string;
  text?: string;
  confidence?: number;
}

/**
 * Export WPS as JSON
 */
export function exportWPSJson(wps: WPSDocument) {
  const blob = new Blob([JSON.stringify(wps, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${wps.wps_number || wps.wps_id || "wps"}-export.json`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Export WPS as professional PDF (ENHANCED VERSION)
 * Includes proper formatting, headers, clause references, and signature blocks
 */
export async function exportWPSPdf(wps: WPSDocument) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  // Helper function to check if we need a new page
  const checkNewPage = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // HEADER - WeldTrack™ Logo and Title
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('WeldTrack™', margin, 15);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Clause-Indexed Welding Procedure Specification', margin, 25);
  doc.text('Generated by ClauseMesh Platform', margin, 32);

  // Document ID and Status (top right)
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text(wps.wps_number || wps.wps_id, pageWidth - margin, 15, { align: 'right' });

  if (wps.revision !== undefined) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Revision ${wps.revision}`, pageWidth - margin, 22, { align: 'right' });
  }

  if (wps.status) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const statusColor = wps.status === 'approved' ? [34, 197, 94] :
                       wps.status === 'draft' ? [234, 179, 8] : [148, 163, 184];
    doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
    doc.text(wps.status.toUpperCase(), pageWidth - margin, 29, { align: 'right' });
  }

  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // TITLE SECTION
  doc.setFillColor(241, 245, 249); // slate-100
  doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(wps.title, margin + 5, yPosition + 10);

  yPosition += 20;

  // METADATA SECTION
  if (wps.metadata) {
    checkNewPage(30);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(71, 85, 105); // slate-600
    doc.text('Document Information', margin, yPosition);
    yPosition += 7;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85); // slate-700

    const metadataItems = [
      wps.metadata.company && `Company: ${wps.metadata.company}`,
      wps.metadata.project && `Project: ${wps.metadata.project}`,
      wps.metadata.created_by && `Created by: ${wps.metadata.created_by}`,
      wps.metadata.created_at && `Created: ${new Date(wps.metadata.created_at).toLocaleString()}`,
      wps.metadata.approved_by && `Approved by: ${wps.metadata.approved_by}`,
      wps.metadata.approved_at && `Approved: ${new Date(wps.metadata.approved_at).toLocaleString()}`,
    ].filter(Boolean);

    metadataItems.forEach(item => {
      if (item) {
        doc.text(item, margin + 5, yPosition);
        yPosition += 5;
      }
    });

    yPosition += 5;
  }

  // WPS FIELDS SECTION
  checkNewPage(40);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 64, 175); // blue-800
  doc.text('Welding Procedure Specification Details', margin, yPosition);
  yPosition += 8;

  // Table header
  doc.setFillColor(59, 130, 246); // blue-500
  doc.rect(margin, yPosition, pageWidth - 2 * margin, 10, 'F');

  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('Field', margin + 3, yPosition + 7);
  doc.text('Value', margin + 50, yPosition + 7);
  doc.text('Code Reference', margin + 130, yPosition + 7);

  yPosition += 10;

  // Table rows
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);

  wps.fields.forEach((field, index) => {
    checkNewPage(20);

    // Alternating row colors
    if (index % 2 === 0) {
      doc.setFillColor(248, 250, 252); // slate-50
      doc.rect(margin, yPosition, pageWidth - 2 * margin, 15, 'F');
    }

    // Field name
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const fieldNameLines = doc.splitTextToSize(field.name, 45);
    doc.text(fieldNameLines, margin + 3, yPosition + 5);

    // Field value
    doc.setFont('helvetica', 'normal');
    const valueLines = doc.splitTextToSize(field.value || '', 75);
    doc.text(valueLines, margin + 50, yPosition + 5);

    // Clause reference with confidence indicator
    if (field.clause) {
      doc.setFontSize(8);
      doc.setTextColor(30, 64, 175); // blue-800
      doc.text(field.clause.id, margin + 130, yPosition + 5);

      if (field.clause.text) {
        doc.setFontSize(7);
        doc.setTextColor(100, 116, 139); // slate-500
        const clauseTextLines = doc.splitTextToSize(field.clause.text, 50);
        doc.text(clauseTextLines, margin + 130, yPosition + 9);
      }

      // Confidence indicator
      if (field.clause.confidence !== undefined) {
        const confidence = Math.round(field.clause.confidence * 100);
        const confidenceColor = confidence >= 90 ? [34, 197, 94] : // green
                               confidence >= 70 ? [234, 179, 8] :   // yellow
                               [239, 68, 68];                        // red
        doc.setFontSize(7);
        doc.setTextColor(confidenceColor[0], confidenceColor[1], confidenceColor[2]);
        doc.text(`${confidence}%`, pageWidth - margin - 10, yPosition + 5, { align: 'right' });
      }

      doc.setTextColor(0, 0, 0);
    }

    yPosition += 15;
  });

  yPosition += 5;

  // CLAUSE INDEX SECTION
  if (wps.clause_index && wps.clause_index.length > 0) {
    checkNewPage(40);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 64, 175);
    doc.text('Referenced Code Clauses', margin, yPosition);
    yPosition += 8;

    wps.clause_index.forEach((clause, index) => {
      checkNewPage(15);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(51, 65, 85);
      doc.text(`${index + 1}. ${clause.id}`, margin + 5, yPosition);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);

      if (clause.clause) {
        doc.text(`Clause: ${clause.clause}`, margin + 10, yPosition + 5);
      }

      if (clause.text) {
        const textLines = doc.splitTextToSize(clause.text, pageWidth - 2 * margin - 15);
        doc.text(textLines, margin + 10, yPosition + 9);
      }

      yPosition += 15;
    });

    yPosition += 5;
  }

  // AUDIT SUMMARY SECTION
  if (wps.audit_summary) {
    checkNewPage(50);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(34, 197, 94); // green-600
    doc.text('Audit Summary', margin, yPosition);
    yPosition += 8;

    doc.setFillColor(240, 253, 244); // green-50
    doc.rect(margin, yPosition, pageWidth - 2 * margin, 40, 'F');

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(22, 101, 52); // green-800

    const auditItems = [
      `Audit Score: ${wps.audit_summary.audit_score || 'N/A'}/100`,
      `Code Compliance: ${wps.audit_summary.code_compliance ? 'PASSED' : 'REVIEW REQUIRED'}`,
      `Essential Variables Qualified: ${wps.audit_summary.essential_variables_qualified ? 'YES' : 'NO'}`,
      `PQR Coverage: ${wps.audit_summary.pqr_coverage_percent || 0}%`,
      `Auto Checks Passed: ${wps.audit_summary.auto_checks?.passed || 0}`,
      `Ready for Production: ${wps.audit_summary.ready_for_production ? 'YES' : 'NO'}`,
    ];

    auditItems.forEach((item, index) => {
      doc.text(item, margin + 5, yPosition + 5 + (index * 6));
    });

    yPosition += 45;
  }

  // SIGNATURE BLOCK
  checkNewPage(50);

  doc.setDrawColor(203, 213, 225); // slate-300
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(51, 65, 85);
  doc.text('Approvals and Signatures', margin, yPosition);
  yPosition += 10;

  // Signature lines
  const col1X = margin + 10;
  const col2X = pageWidth / 2 + 10;

  // Prepared by
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Prepared by:', col1X, yPosition);
  doc.line(col1X, yPosition + 10, col1X + 60, yPosition + 10);
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text('Name / Date', col1X, yPosition + 14);

  // Approved by
  doc.setFontSize(9);
  doc.setTextColor(51, 65, 85);
  doc.text('Approved by:', col2X, yPosition);
  doc.line(col2X, yPosition + 10, col2X + 60, yPosition + 10);
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text('Name / Date', col2X, yPosition + 14);

  yPosition += 25;

  // FOOTER
  const footerY = pageHeight - 15;
  doc.setFontSize(7);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by WeldTrack™ Clause-Indexed WPS Generator', margin, footerY);
  doc.text(`Page 1 of ${doc.internal.pages.length - 1}`, pageWidth - margin, footerY, { align: 'right' });
  doc.text(new Date().toLocaleString(), pageWidth / 2, footerY, { align: 'center' });

  doc.setFontSize(6);
  doc.text('This is a computer-generated document. Digital signature verification available via blockchain audit trail.', pageWidth / 2, footerY + 3, { align: 'center' });

  // Save PDF
  doc.save(`${wps.wps_number || wps.wps_id || 'WPS'}-Rev${wps.revision || 0}.pdf`);
}

/**
 * Export SVG from canvas/stage
 */
export function exportSvg(svgEl: SVGSVGElement | HTMLCanvasElement, filename = "drawing.svg") {
  if (svgEl instanceof SVGSVGElement) {
    const serializer = new XMLSerializer();
    const source = serializer.serializeToString(svgEl);
    const blob = new Blob([source], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  } else if (svgEl instanceof HTMLCanvasElement) {
    // Export canvas as PNG
    svgEl.toBlob((blob) => {
      if (blob) {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename.replace('.svg', '.png');
        a.click();
        URL.revokeObjectURL(url);
      }
    });
  }
}

/**
 * Export turnover bundle (ZIP with WPS PDF + JSON + supporting docs)
 * Requires JSZip library
 */
export async function exportTurnoverBundle(wps: WPSDocument, pqrs: any[] = []) {
  // This would require JSZip library
  // Placeholder for future implementation
  console.warn('Turnover bundle export requires JSZip library - coming soon');

  // For now, just export WPS JSON and PDF separately
  exportWPSJson(wps);
  await exportWPSPdf(wps);
}
